name: CI-FI Madhur Hindi Final VO

on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/cifi-madhur-final.yml'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - run: echo render complete
